{
 "title": "SNMP Alerts",
 "description": "Notes: critical(1) severity is the same value for NS and XS, and that is why there is only one query for critical",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sourceip",
    "label": "Source IP",
    "query": {}
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": {}
   },
   {
    "name": "category",
    "label": "MIB Category",
    "query": {}
   },
   { "name": "free_form_filter", "label": "Text Filter" }
  ]
 },
 "panels": [
  {
   "title": "Unknown",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=\"loki.source.snmp\", samm_severity=\"6\"} [$__auto])",
     "legendFormat": "{{samm_severity}}"
    }
   ]
  },
  {
   "title": "Informational",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=\"loki.source.snmp\", samm_severity=\"5\"} [$__auto])",
     "legendFormat": "{{samm_severity}}"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=\"loki.source.snmp\", samm_severity=\"4\"} [$__auto])",
     "legendFormat": "{{samm_severity}}"
    }
   ]
  },
  {
   "title": "Minor alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=\"loki.source.snmp\", samm_severity=\"3\"} [$__auto])",
     "legendFormat": "{{samm_severity}}"
    }
   ]
  },
  {
   "title": "Major",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=\"loki.source.snmp\", samm_severity=\"2\"} [$__auto])",
     "legendFormat": "{{samm_severity}}"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({service_name=\"loki.source.snmp\", samm_severity=\"1\"} [$__auto])"
    }
   ]
  },
  {
   "title": "SNMP Traps",
   "type": "logs",
   "gridPos": { "h": 16, "w": 15, "x": 0, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{snmptrapd_category=~\"$category\", samm_severity=~\"$severity\", snmptrapd_sourceip=~\"$sourceip\", service_name=\"loki.source.snmp\"} |~ `$free_form_filter`"
    }
   ]
  },
  {
   "title": "Alerts by severity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "(count_over_time({service_name=\"loki.source.snmp\"} [$__interval]))",
     "legendFormat": "{{samm_severity}}"
    }
   ]
  }
 ]
}