{
 "title": "VM Info v3.4",
 "tags": [
  "VMInfo",
  "XenServer"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds_samm_prometheus", "query": "prometheus" },
   { "name": "vm_uuid", "label": "VM_UUID", "query": { "query": "query_result(xen_vm_info)" } },
   {
    "name": "vm_name_label",
    "label": "VM Name",
    "query": {
     "query": "query_result(xen_vm_info{uuid=\"$vm_uuid\"})"
    }
   },
   {
    "name": "vm_power_state",
    "label": "Power State",
    "query": {
     "query": "query_result(xen_vm_info{uuid=\"$vm_uuid\"})"
    }
   },
   {
    "name": "vm_resident_on",
    "label": "Resident On",
    "query": {
     "query": "query_result(xen_vm_info{uuid=\"$vm_uuid\"})"
    }
   },
   {
    "name": "vm_os_version_distro",
    "label": "OS",
    "query": {
     "query": "query_result(xen_vm_info{name_label=\"$vm_name_label\"} * on (guest_metrics) group_left (os_version_distro) label_replace(xen_vm_guest_metrics_info, \"guest_metrics\", \"$1\", \"uuid\", \"(.*)\"))"
    }
   },
   {
    "name": "vm_ip_address1",
    "label": "VP IP Address",
    "query": {
     "query": "query_result(xen_vm_info{name_label=\"$vm_name_label\"} * on (guest_metrics) group_left (networks) label_replace(xen_vm_guest_metrics_info, \"guest_metrics\", \"$1\", \"uuid\", \"(.*)\"))"
    }
   },
   {
    "name": "vm_ip_address2",
    "label": "VP IP Address",
    "query": {
     "query": "query_result(xen_vm_info{name_label=\"$vm_name_label\"} * on (guest_metrics) group_left (networks) label_replace(xen_vm_guest_metrics_info, \"guest_metrics\", \"$1\", \"uuid\", \"(.*)\"))"
    }
   },
   {
    "name": "vm_guest_metrics_uuid",
    "query": {
     "query": "label_values(xen_vm_info{uuid=\"$vm_uuid\"},guest_metrics)"
    }
   },
   {
    "name": "vm_netbios_name",
    "query": {
     "query": "label_values(xen_vm_guest_metrics_info{uuid=\"$vm_guest_metrics_uuid\"},netbios_name)"
    }
   },
   {
    "name": "vm_fqdn",
    "query": {
     "query": "query_result(cim_os_lastbootuptime{instance=~\"((?i)${vm_name_label})\"})"
    }
   },
   {
    "name": "xen_host_name",
    "query": {
     "query": "label_values(xen_host_info{uuid=\"$vm_resident_on\"},hostname)"
    }
   },
   {
    "name": "xen_host_ip",
    "query": {
     "query": "label_values(xen_host_info{uuid=\"$vm_resident_on\"},address)"
    }
   },
   {
    "name": "xen_host_uuid",
    "query": {
     "query": "label_values(xen_host_info{uuid=\"$vm_resident_on\"},uuid)"
    }
   },
   {
    "name": "xen_pool_name",
    "query": {
     "query": "label_values(xen_pool_info{instance=\"$xen_host_instance\"},name_label)"
    }
   },
   {
    "name": "xen_host_instance",
    "query": {
     "query": "label_values(xen_host_info{uuid=\"$vm_resident_on\"},instance)"
    }
   },
   {
    "name": "xen_pool_uuid",
    "query": {
     "query": "label_values(xen_pool_info{instance=\"$xen_host_instance\"},uuid)"
    }
   },
   { "name": "grafanaurl", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "xen_vm_info{uuid=\"$vm_uuid\"}",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "CPU Info",
   "type": "gauge",
   "description": "Basic CPU Info",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(xen_vm_cpu{uuid=\"$vm_uuid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1-((xen_vm_memory_internal_free{uuid=\"$vm_uuid\"} / 1024 / 1024)/(xen_vm_memory{uuid=\"$vm_uuid\"} / 1024 / 1048576))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "xen_vm_info{uuid=\"$vm_uuid\"}",
     "legendFormat": "Host ${xen_host_name} (${xen_host_ip})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "xen_vm_info{uuid=\"$vm_uuid\"}",
     "legendFormat": "${xen_pool_name}"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "xen_vm_vbd_latency{uuid=\"$vm_uuid\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Power State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "xen_vm_info{uuid=\"$vm_uuid\"}",
     "legendFormat": "{{power_state}}"
    }
   ]
  },
  {
   "title": "VM Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(xen_vm_memory{uuid=\"$vm_uuid\"} /1024)/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IP Address",
   "type": "text",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 3 },
   "options": {
    "content": "<h5>${vm_ip_address1}</h5>\n<h5>${vm_ip_address2}</h5>\n"
   }
  },
  {
   "title": "Interfaces",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(xen_vm_vif_rx{uuid=\"$vm_uuid\"})/1024",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "(xen_vm_vif_tx{uuid=\"$vm_uuid\"})/1024",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "VM Basic Information",
   "type": "text",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "options": {
    "content": "<div style='background-color: #1e1e1e; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1);'>\r\n\t<table style='width: 100%; border-collapse: collapse;'>\r\n\t\t<tr style='border-bottom: 1px solid #2d2d2d;'>\r\n\t\t\t<th style='text-align: left; padding: 8px; color: #8e8e8e;'>VM Name</th>\r\n\t\t\t<td style='padding: 8px; color: #ffffff;'>${vm_name_label}</td>\r\n\t\t</tr>\r\n\t\t<tr style='border-bottom: 1px solid #2d2d2d;'>\r\n\t\t\t<th style='text-align: left; padding: 8px; color: #8e8e8e;'>Power State</th>\r\n\t\t\t<td style='padding: 8px; color: #ffffff;'>${vm_power_state}</td>\r\n\t\t</tr>\r\n\t\t<tr style='border-bottom: 1px solid #2d2d2d;'>\r\n\t\t\t<th style='text-align: left; padding: 8px; color: #8e8e8e;'>Resident On</th>\r\n\t\t\t<td style='padding: 8px; color: #ffffff;'>${xen_host_name} (${xen_host_ip})</td>\r\n\t\t</tr>\r\n\t\t<tr style='border-bottom: 1px solid #2d2d2d;'>\r\n\t\t\t<th style='text-align: left; padding: 8px; color: #8e8e8e;'>UUID</th>\r\n\t\t\t<td style='padding: 8px; color: #ffffff;'>${vm_uuid}</td>\r\n\t\t</tr>\r\n\t</table>\r\n</div>\r\n"
   }
  },
  {
   "title": "Read / Write Disk Latency",
   "type": "timeseries",
   "description": "Read / Write Latency",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "-xen_vm_vbd_write_latency{uuid=\"$vm_uuid\"}",
     "legendFormat": "WR Disk: {{device}}"
    },
    {
     "expr": "xen_vm_vbd_read_latency{uuid=\"$vm_uuid\"}",
     "legendFormat": "RD Disk: {{device}}"
    }
   ]
  },
  {
   "title": "Total IOPs per Disk",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "xen_vm_vbd_iops_read{uuid=\"$vm_uuid\"}",
     "legendFormat": "Disk {{device}}"
    },
    {
     "expr": "-xen_vm_vbd_iops_write{uuid=\"$vm_uuid\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "CPU Core Performance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "xen_vm_cpu{uuid=\"$vm_uuid\"}",
     "legendFormat": "Core: {{index}}"
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-xen_vm_vif_rx{uuid=\"$vm_uuid\"}",
     "legendFormat": "RX:{{device}}"
    },
    {
     "expr": "xen_vm_vif_tx{uuid=\"$vm_uuid\"}",
     "legendFormat": "TX:{{device}}"
    }
   ]
  }
 ]
}