{
 "title": "XS Host Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "xs_host_hostname",
    "label": "XS Host Hostname",
    "query": {
     "query": "label_values(xen_host_info,name_label)"
    }
   },
   {
    "name": "xs_host_uuid",
    "query": {
     "query": "label_values(xen_host_info{name_label=\"$xs_host_hostname\"},uuid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_host_boot_time{uuid=\"$xs_host_uuid\"}",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 1, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_host_cpu_avg{uuid=\"$xs_host_uuid\"}",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "AVG CPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "xen_host_cpu_avg{uuid=\"$xs_host_uuid\"}",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 1, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-(xen_host_memory_free_kib{uuid=\"$xs_host_uuid\"}/xen_host_memory_total_kib{uuid=\"$xs_host_uuid\"})",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "RAM Load Percentage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(xen_host_memory_free_kib{uuid=\"$xs_host_uuid\"}/xen_host_memory_total_kib{uuid=\"$xs_host_uuid\"})",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  { "title": "Alert Panel", "type": "alertlist", "gridPos": { "h": 8, "w": 13, "x": 0, "y": 10 } },
  {
   "title": "Interfaces TX",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "xen_host_pif_rx{uuid=\"$xs_host_uuid\"}",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "Interfaces RX",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-xen_host_pif_rx{uuid=\"$xs_host_uuid\"}",
     "legendFormat": "{{name_label}}"
    }
   ]
  }
 ]
}