{
 "title": "XS Host Info R",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "xen_host_uuid", "label": "XenServer Host", "query": { "query": "query_result(xen_host_info)" } },
   {
    "name": "xen_host_instance",
    "label": "xen_host_instance",
    "query": {
     "query": "label_values(xen_host_info{uuid=\"$xen_host_uuid\"},instance)"
    }
   },
   {
    "name": "xen_vm_hostname",
    "query": {
     "query": "label_values(xen_vm_info{instance=\"$xen_host_instance\", power_state=\"Running\"},name_label)"
    }
   },
   {
    "name": "xen_host_hostname",
    "label": "xen_host_hostname",
    "query": {
     "query": "label_values(xen_host_info{uuid=\"$xen_host_uuid\"},hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_host_info{uuid=\"$xen_host_uuid\"}",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "CPU Info",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "xen_host_cpu_avg{uuid=\"$xen_host_uuid\"}",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "Host Load per physical CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_host_hostload{uuid=\"$xen_host_uuid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_pool_info{instance=\"$xen_host_instance\"}",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "Address",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_host_info{uuid=\"$xen_host_uuid\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_host_info{uuid=\"$xen_host_uuid\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_host_info{uuid=\"$xen_host_uuid\"}",
     "legendFormat": "{{system_manufacturer}} {{system_product_name}}"
    }
   ]
  },
  {
   "title": "Serial Number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_host_info{uuid=\"$xen_host_uuid\"}",
     "legendFormat": "{{system_serial_number}}"
    }
   ]
  },
  {
   "title": "IOPS Read / Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "xen_host_sr_iops_read{uuid=\"$xen_host_uuid\"} \r\n    * on (  sr_uuid) group_left (sr_name)\r\n    (\r\n        label_replace ( xen_sr_info, \"sr_name\", \"$1\", \"name_label\", \"(.*)\" )\r\n   )",
     "legendFormat": "{{sr_name}}"
    },
    {
     "expr": "-xen_host_sr_iops_write{uuid=\"$xen_host_uuid\"} \r\n    * on (  sr_uuid) group_left (sr_name)\r\n    (\r\n        label_replace ( xen_sr_info, \"sr_name\", \"$1\", \"name_label\", \"(.*)\" )\r\n   )",
     "legendFormat": "{{sr_name}}"
    }
   ]
  },
  {
   "title": "CPU AVG",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_host_cpu_avg{uuid=\"$xen_host_uuid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-xen_host_memory_free_kib{uuid=\"$xen_host_uuid\"}/xen_host_memory_total_kib{uuid=\"$xen_host_uuid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "-xen_host_pif_rx{uuid=\"$xen_host_uuid\"}",
     "legendFormat": "rx-{{device}}"
    },
    {
     "expr": "xen_host_pif_tx{uuid=\"$xen_host_uuid\"}\r\n",
     "legendFormat": "tx-{{device}}"
    }
   ]
  },
  {
   "title": "SR Read / Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "xen_host_sr_read_latency{uuid=\"$xen_host_uuid\"} \r\n    * on (  sr_uuid) group_left (sr_name)\r\n    (\r\n        label_replace ( xen_sr_info, \"sr_name\", \"$1\", \"name_label\", \"(.*)\" )\r\n   )",
     "legendFormat": "{{sr_name}}"
    },
    {
     "expr": "-xen_host_sr_read_latency{uuid=\"$xen_host_uuid\"} \r\n    * on (  sr_uuid) group_left (sr_name)\r\n    (\r\n        label_replace ( xen_sr_info, \"sr_name\", \"$1\", \"name_label\", \"(.*)\" )\r\n   )",
     "legendFormat": "{{sr_name}}"
    }
   ]
  },
  {
   "title": "VM Running on $xen_host_hostname",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_vm_info{resident_on=\"$xen_host_uuid\", power_state=\"Running\"}",
     "legendFormat": "{{name_label}}"
    }
   ]
  }
 ]
}