{
 "title": "XS Pool Info",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "xen_pool_uuid", "label": "XEN_POOL_UUID", "query": { "query": "query_result(xen_pool_info)" } },
   {
    "name": "xen_host_uuid",
    "label": "Host UUID",
    "query": {
     "query": "label_values({pool_uuid=\"$xen_pool_uuid\"},name_label)"
    }
   },
   {
    "name": "xen_host_instance",
    "label": "Host Instance IP",
    "query": {
     "query": "label_values({pool_uuid=\"$xen_pool_uuid\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$xen_pool_uuid",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_pool_info{uuid=\"$xen_pool_uuid\"}",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "Hosts Running in $xen_pool_uuid",
   "type": "stat",
   "gridPos": { "h": 10, "w": 19, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (host_name_label) (\r\n    xen_vm_info\r\n    * on (resident_on) group_left (host_name_label) (\r\n        label_replace (\r\n            label_replace ( \r\n                xen_host_info{pool_uuid=\"$xen_pool_uuid\"}\r\n                , \"host_name_label\", \"$1\" , \"name_label\", \"(.*)\"\r\n            )\r\n            , \"resident_on\" , \"$1\", \"uuid\" , \"(.*)\"\r\n        )\r\n    )\r\n)",
     "legendFormat": "{{host_name_label}}"
    }
   ]
  },
  {
   "title": "Host AVG Load",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_host_hostload{instance=\"$xen_host_instance\"}",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "Host AVG CPU",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xen_host_cpu_avg{instance=\"$xen_host_instance\"}",
     "legendFormat": "{{name_label}}"
    }
   ]
  },
  {
   "title": "Host RAM Load",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1-xen_host_memory_free_kib{instance=\"$xen_host_instance\"} / xen_host_memory_total_kib{instance=\"$xen_host_instance\"}",
     "legendFormat": "{{name_label}}"
    }
   ]
  }
 ]
}