{
 "title": "SYSLOG Dashboard",
 "description": "Syslog Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Host",
    "query": {}
   },
   { "name": "filter", "label": "Severity", "query": "info,debug,warn,error,critical" },
   { "name": "smooth", "label": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h,2h" },
   { "name": "free_form_filter", "label": "Text filter" }
  ]
 },
 "panels": [
  {
   "title": "Counts By Host: $hostname - Severity: \"$filter\" - \"$free_form_filter\" (Filtered)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(hostname) (count_over_time({hostname=~\"$hostname\", component=\"loki.source.syslog\"} |~ `$filter` |~ `$free_form_filter` [$__auto]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Logs By Host - \"$filter\" - \"$free_form_filter\" (Filtered)",
   "type": "logs",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 4 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{hostname=~\"$hostname\", component=\"loki.source.syslog\"} |~ `$filter` |~ `$free_form_filter`"
    }
   ]
  },
  {
   "title": "Log Line Counts By Host (Unfiltered)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(hostname) (count_over_time({component=\"loki.source.syslog\"}  |~ `$filter` |~ `$free_form_filter` [$__auto]))",
     "legendFormat": "{{hostname}}"
    }
   ]
  }
 ]
}